version: '3.9'

services:

  nginx-balancer:
    build: ./nginx-balancer/
    ports:
      - "8080:80"
    networks: 
      - backend
      - frontend

  nginx-node:
    build: ./nginx-node/
    volumes:
      - ./nginx-node/site/:/var/www/html
    depends_on:
      - nginx-balancer
    networks: 
      - backend

networks:
  # The presence of these objects is sufficient to define them
  frontend: {}
  backend: {}